// <auto-generated />
using DeveloperTeamInsights.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeveloperTeamInsights.Migrations
{
    [DbContext(typeof(DeveloperTeamInsightsContext))]
    [Migration("20250223163807_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DeveloperTeamInsights.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeveloperName")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberActivePRs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberDocumentsGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberDocumentsReviewed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberReviewsConducted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberTasksWorked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });
#pragma warning restore 612, 618
        }
    }
}
